apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders_payments-micro
  name: orders_payments-micro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders_payments-micro
  template:
    metadata:
      labels:
        app: orders_payments-micro
    spec:
      containers:
        - name: my-orders_payments-micro
          image: 384067822530.dkr.ecr.us-east-1.amazonaws.com/prod-ecr:mystreet-orders-payments
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders_payments-micro
    k8s-app: orders_payments-micro
  name: orders_payments-micro
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: orders_payments-micro
